name: requests
description: a flutter library that helps with http requests and stored cookies
version: 4.3.0
homepage: https://github.com/jossef/requests
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.2
  hex: ^0.2.0
  http: ^0.13.4
  quiver: ^3.1.0
  universal_io: ^2.0.4
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
